"""Generate the bundled synthetic IFU cubes (deterministic, MIT like the rest of this repo).

rbcodes' own example cubes are too large to bundle (``long_radd.fits`` is 65 MB and the Eiger mock
data 111 MB, against a 50 MB budget for sample data), so the IFU template ships a small cube built
here instead. ``synthetic_ifu_icubes.fits`` and its ``_vcubes`` variance sidecar (the KCWI
naming, so the sidecar lookup in ``core.io.load_cube`` is exercised too) hold the cube the IFU
template uses:
160 x 40 x 36 with a rotating disc (a linear velocity gradient of +-120 km/s across the field), a
fainter companion clump offset in velocity, a flat continuum and Gaussian noise. The velocity field
is analytic, which is what makes the cube a usable reference for the moment-map tests.

The older ``synthetic_kcwi_*`` pair (phase 04) predates this script and is not regenerated here.

Run with ``uv run --directory backend python ../packs/rbcodes/sample_data/make_cube.py``.
"""

from __future__ import annotations

from pathlib import Path

import numpy as np
from astropy.io import fits

C_KMS = 2.998e5
HERE = Path(__file__).resolve().parent

# --- the phase-08 cube ---------------------------------------------------------------------------

NZ, NY, NX = 160, 40, 36
WAVE0, DWAVE = 4900.0, 1.0
"""4900-5059 A at 1 A per channel: [O III] 5007 sits in the middle with room for continuum."""
LAMBDA_REST = 5007.0
DISC_CENTRE = (17.5, 19.5)
DISC_SIGMA = (7.0, 5.0)
DISC_PEAK = 120.0
VELOCITY_GRADIENT = 8.0
"""km/s per pixel along x: +-120 km/s across the 36-pixel field (the analytic velocity field)."""
LINE_SIGMA_KMS = 65.0
COMPANION = {"centre": (29.0, 32.0), "sigma": 2.4, "peak": 45.0, "velocity": 180.0}
CONTINUUM = 3.0
NOISE = 0.35
SEED = 1908


def velocity_field(ny: int = NY, nx: int = NX) -> np.ndarray:
    """The disc's line-of-sight velocity in km/s at every spaxel (a linear gradient along x)."""
    y, x = np.mgrid[0:ny, 0:nx]
    return (x - DISC_CENTRE[0]) * VELOCITY_GRADIENT


def build_ifu_cube() -> tuple[np.ndarray, np.ndarray, np.ndarray, fits.Header]:
    """The cube, its variance, the wavelength axis and the header."""
    rng = np.random.default_rng(SEED)
    wave = WAVE0 + DWAVE * np.arange(NZ, dtype=np.float64)
    y, x = np.mgrid[0:NY, 0:NX]

    disc = DISC_PEAK * np.exp(
        -(((x - DISC_CENTRE[0]) / DISC_SIGMA[0]) ** 2 + ((y - DISC_CENTRE[1]) / DISC_SIGMA[1]) ** 2)
        / 2.0
    )
    clump = COMPANION["peak"] * np.exp(
        -((x - COMPANION["centre"][0]) ** 2 + (y - COMPANION["centre"][1]) ** 2)
        / (2.0 * COMPANION["sigma"] ** 2)
    )
    velocity = velocity_field()
    sigma_wave = LINE_SIGMA_KMS / C_KMS * LAMBDA_REST

    cube = np.full((NZ, NY, NX), CONTINUUM, dtype=np.float64)
    clump_velocity = np.full_like(velocity, COMPANION["velocity"])
    for amplitude, vel in ((disc, velocity), (clump, clump_velocity)):
        centre = LAMBDA_REST * (1.0 + vel / C_KMS)
        profile = np.exp(-((wave[:, None, None] - centre[None]) ** 2) / (2.0 * sigma_wave**2))
        cube += amplitude[None] * profile
    var = np.full_like(cube, NOISE**2)
    cube += rng.normal(scale=NOISE, size=cube.shape)

    header = fits.Header()
    header["INSTRUME"] = "KCWI"
    header["OBJECT"] = "Synthetic disc"
    header["BUNIT"] = "1e-16 erg / (s cm2 Angstrom)"
    header["CTYPE1"] = "RA---TAN"
    header["CTYPE2"] = "DEC--TAN"
    header["CTYPE3"] = "AWAV"
    header["CUNIT1"] = "deg"
    header["CUNIT2"] = "deg"
    header["CUNIT3"] = "Angstrom"
    header["CRVAL1"] = 150.1
    header["CRVAL2"] = 2.2
    header["CRVAL3"] = WAVE0
    header["CRPIX1"] = 18.0
    header["CRPIX2"] = 20.0
    header["CRPIX3"] = 1.0
    header["CDELT1"] = -0.0001  # 0.36" spaxels
    header["CDELT2"] = 0.0001
    header["CD3_3"] = DWAVE
    header["RADESYS"] = "ICRS"
    header["EQUINOX"] = 2000.0
    header["COMMENT"] = "Synthetic IFU cube generated by sample_data/make_cube.py (seed 1908)"
    return cube.astype(np.float32), var.astype(np.float32), wave, header


def write(path: Path, data: np.ndarray, header: fits.Header) -> None:
    fits.PrimaryHDU(data=data, header=header).writeto(path, overwrite=True)
    print(f"wrote {path.name} ({path.stat().st_size / 1e6:.1f} MB)")


def main() -> None:
    cube, var, _, header = build_ifu_cube()
    write(HERE / "synthetic_ifu_icubes.fits", cube, header)
    write(HERE / "synthetic_ifu_vcubes.fits", var, header)


if __name__ == "__main__":
    main()
