/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/health': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Health
     * @description Return ``ok`` and the server version.
     */
    get: operations['health_api_health_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/nodes': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * List Nodes
     * @description Every registered node schema, sorted by id; optionally filtered by exact category.
     */
    get: operations['list_nodes_api_nodes_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/nodes/{node_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get Node
     * @description One node schema by id.
     */
    get: operations['get_node_api_nodes__node_id__get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/packs': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * List Packs
     * @description Discovered packs, including the ones that failed to load (with their error).
     */
    get: operations['list_packs_api_packs_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/system': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * System
     * @description Describe the running server: versions, workspace, disk, packs.
     */
    get: operations['system_api_system_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/types': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * List Types
     * @description Every registered port type, sorted by id.
     */
    get: operations['list_types_api_types_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components['schemas']['ValidationError'][]
    }
    /**
     * HealthResponse
     * @description Liveness probe payload.
     */
    HealthResponse: {
      /**
       * Status
       * @constant
       */
      status: 'ok'
      /** Version */
      version: string
    }
    /**
     * NodeSpec
     * @description Everything the frontend and engine need to know about a node type.
     */
    NodeSpec: {
      /** Category */
      category: string
      /**
       * Cost
       * @default cheap
       * @enum {string}
       */
      cost: 'cheap' | 'expensive' | 'auto'
      /**
       * Deprecated
       * @default false
       */
      deprecated: boolean
      /**
       * Description
       * @default
       */
      description: string
      /** Editor */
      editor?: string | null
      /**
       * Expand
       * @default false
       */
      expand: boolean
      /**
       * Experimental
       * @default false
       */
      experimental: boolean
      /**
       * Fingerprint
       * @description True when the node declares a ``fingerprint`` callable.
       * @default false
       */
      fingerprint: boolean
      /** Icon */
      icon?: string | null
      /** Id */
      id: string
      /**
       * Inputs
       * @default []
       */
      inputs: components['schemas']['PortSpec'][]
      /**
       * Is Async
       * @default false
       */
      is_async: boolean
      /**
       * Module
       * @default
       */
      module: string
      /** Name */
      name: string
      /**
       * Outputs
       * @default []
       */
      outputs: components['schemas']['PortSpec'][]
      /** Pack */
      pack?: string | null
      /**
       * Param Docs
       * @default {}
       */
      param_docs: {
        [key: string]: string
      }
      /**
       * Params
       * @default []
       */
      params: components['schemas']['ParamSpec'][]
      /** Preview */
      preview?: string | null
      /**
       * Version
       * @default 1.0.0
       */
      version: string
    }
    /**
     * PackInfo
     * @description Summary of a discovered node pack (full detail at ``/api/packs``).
     */
    PackInfo: {
      /**
       * Enabled
       * @default true
       */
      enabled: boolean
      /** Error */
      error?: string | null
      /** Name */
      name: string
      /**
       * Node Count
       * @default 0
       */
      node_count: number
      /** Version */
      version: string
    }
    /**
     * PackLoadError
     * @description Recorded (not raised) when a pack's entry point fails to import or register.
     */
    PackLoadError: {
      /** Entry Point */
      entry_point: string
      /** Error */
      error: string
      /** Pack */
      pack: string
      /**
       * Traceback
       * @default
       */
      traceback: string
    }
    /**
     * PackRecord
     * @description A discovered pack (entry point in the ``astro_canvas.nodes`` group).
     */
    PackRecord: {
      /** Distribution */
      distribution?: string | null
      /**
       * Enabled
       * @default true
       */
      enabled: boolean
      /** Entry Point */
      entry_point: string
      error?: components['schemas']['PackLoadError'] | null
      /** Name */
      name: string
      /**
       * Node Count
       * @default 0
       */
      node_count: number
      /**
       * Type Count
       * @default 0
       */
      type_count: number
      /**
       * Version
       * @default unknown
       */
      version: string
    }
    /**
     * ParamSpec
     * @description A widget-rendered parameter. Any param can be linked to become an input port.
     */
    ParamSpec: {
      /**
       * Advanced
       * @default false
       */
      advanced: boolean
      /** Default */
      default?: unknown
      /**
       * Description
       * @default
       */
      description: string
      /**
       * Json Schema
       * @description Self-contained JSON Schema (draft 2020-12) including default/constraints.
       */
      json_schema: {
        [key: string]: unknown
      }
      /** Label */
      label: string
      /**
       * Link Type
       * @description Port type id the param becomes when linked (``astro.Float`` etc.).
       */
      link_type: string
      /**
       * Linkable
       * @default true
       */
      linkable: boolean
      /** Name */
      name: string
      /**
       * Required
       * @default false
       */
      required: boolean
      /** Step */
      step?: number | null
      /** Unit */
      unit?: string | null
      /** Widget */
      widget?: string | null
    }
    /**
     * PortSpec
     * @description An input or output port.
     */
    PortSpec: {
      /**
       * Description
       * @default
       */
      description: string
      /**
       * Lazy
       * @default false
       */
      lazy: boolean
      /** Name */
      name: string
      /**
       * Required
       * @default true
       */
      required: boolean
      /**
       * Type
       * @description Port type id, e.g. ``astro.Spectrum1D``.
       */
      type: string
    }
    /**
     * PortTypeSpec
     * @description A registered port type.
     */
    PortTypeSpec: {
      /**
       * Color
       * @default #888888
       */
      color: string
      /**
       * Compatible With
       * @default []
       */
      compatible_with: string[]
      /**
       * Description
       * @default
       */
      description: string
      /** Id */
      id: string
      /**
       * Json Schema
       * @default {}
       */
      json_schema: {
        [key: string]: unknown
      }
      /**
       * Module
       * @default
       */
      module: string
      /** Name */
      name: string
      /** Pack */
      pack?: string | null
      /** Summary Renderer */
      summary_renderer?: string | null
    }
    /**
     * SystemInfo
     * @description Environment report shown in the shell's About panel.
     */
    SystemInfo: {
      /** Disk Free Bytes */
      disk_free_bytes: number
      /** Disk Total Bytes */
      disk_total_bytes: number
      /** Packs */
      packs: components['schemas']['PackInfo'][]
      /** Platform */
      platform: string
      /** Python */
      python: string
      /** Version */
      version: string
      /** Workspace */
      workspace: string
      /** Workspace Exists */
      workspace_exists: boolean
    }
    /** ValidationError */
    ValidationError: {
      /** Context */
      ctx?: Record<string, never>
      /** Input */
      input?: unknown
      /** Location */
      loc: (string | number)[]
      /** Message */
      msg: string
      /** Error Type */
      type: string
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  health_api_health_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HealthResponse']
        }
      }
    }
  }
  list_nodes_api_nodes_get: {
    parameters: {
      query?: {
        category?: string | null
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['NodeSpec'][]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_node_api_nodes__node_id__get: {
    parameters: {
      query?: never
      header?: never
      path: {
        node_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['NodeSpec']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  list_packs_api_packs_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['PackRecord'][]
        }
      }
    }
  }
  system_api_system_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['SystemInfo']
        }
      }
    }
  }
  list_types_api_types_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['PortTypeSpec'][]
        }
      }
    }
  }
}
