/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/health': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Health
     * @description Return ``ok`` and the server version.
     */
    get: operations['health_api_health_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/nodes': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * List Nodes
     * @description Every registered node schema, sorted by id; optionally filtered by exact category.
     */
    get: operations['list_nodes_api_nodes_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/nodes/{node_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get Node
     * @description One node schema by id.
     */
    get: operations['get_node_api_nodes__node_id__get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/outputs/{node_id}/{port}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get Output
     * @description A finished node's output. ``decimate``/``range`` apply to 1-d spectrum-like values.
     */
    get: operations['get_output_api_outputs__node_id___port__get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/packs': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * List Packs
     * @description Discovered packs, including the ones that failed to load (with their error).
     */
    get: operations['list_packs_api_packs_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/runs': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * List Runs
     * @description Recent runs (persisted across restarts), newest first.
     */
    get: operations['list_runs_api_runs_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/runs/{run_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get Run */
    get: operations['get_run_api_runs__run_id__get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/runs/{run_id}/cancel': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Cancel Run
     * @description Cancel the run if it is still executing (kills process workers, flags threads).
     */
    post: operations['cancel_run_api_runs__run_id__cancel_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/system': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * System
     * @description Describe the running server: versions, workspace, disk, packs.
     */
    get: operations['system_api_system_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/templates': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get Templates
     * @description Templates shipped by the installed packs.
     */
    get: operations['get_templates_api_templates_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/templates/{template_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get Template
     * @description The template document itself (not stored; instantiate to get an editable workflow).
     */
    get: operations['get_template_api_templates__template_id__get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/templates/{template_id}/instantiate': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Instantiate Template
     * @description Create a new workflow from the template (fresh id; ``meta.template`` records the origin).
     */
    post: operations['instantiate_template_api_templates__template_id__instantiate_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/types': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * List Types
     * @description Every registered port type, sorted by id.
     */
    get: operations['list_types_api_types_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/workflows': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * List Workflows
     * @description Stored workflows, most recently modified first.
     */
    get: operations['list_workflows_api_workflows_get']
    put?: never
    /**
     * Create Workflow
     * @description Store a new document (a fresh id is assigned when the given one already exists).
     */
    post: operations['create_workflow_api_workflows_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/workflows/{workflow_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get Workflow */
    get: operations['get_workflow_api_workflows__workflow_id__get']
    /**
     * Put Workflow
     * @description Replace the document; the engine recompiles it and auto-runs cheap dirty nodes.
     */
    put: operations['put_workflow_api_workflows__workflow_id__put']
    post?: never
    /** Delete Workflow */
    delete: operations['delete_workflow_api_workflows__workflow_id__delete']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/workflows/{workflow_id}/batch': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Start Batch
     * @description Run the stored document once per row; returns immediately with the batch record.
     */
    post: operations['start_batch_api_workflows__workflow_id__batch_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/workflows/{workflow_id}/batch/{batch_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get Batch
     * @description The batch's per-row states and the results assembled so far.
     */
    get: operations['get_batch_api_workflows__workflow_id__batch__batch_id__get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/workflows/{workflow_id}/batch/{batch_id}/cancel': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Cancel Batch
     * @description Stop queued rows and cancel the ones in flight (expensive nodes have their worker killed).
     */
    post: operations['cancel_batch_api_workflows__workflow_id__batch__batch_id__cancel_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/workflows/{workflow_id}/run': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Start Run
     * @description Queue a run (stale expensive nodes included) and return its id immediately.
     */
    post: operations['start_run_api_workflows__workflow_id__run_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/workflows/{workflow_id}/settings': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get Settings
     * @description The scheduler switches for one workflow.
     */
    get: operations['get_settings_api_workflows__workflow_id__settings_get']
    put?: never
    /**
     * Update Settings
     * @description Toggle auto-run; enabling it schedules any dirty cheap nodes right away.
     */
    post: operations['update_settings_api_workflows__workflow_id__settings_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/workflows/{workflow_id}/status': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Workflow Status
     * @description Compile issues and the state of every node (what a reconnecting client needs).
     */
    get: operations['workflow_status_api_workflows__workflow_id__status_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/workflows/{workflow_id}/versions': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * List Versions
     * @description Auto-snapshots (every changed save) and labelled versions, newest first.
     */
    get: operations['list_versions_api_workflows__workflow_id__versions_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/workflows/{workflow_id}/versions/{version_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get Version */
    get: operations['get_version_api_workflows__workflow_id__versions__version_id__get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/workspace': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Workspace Info
     * @description The active workspace folder and recently used ones.
     */
    get: operations['workspace_info_api_workspace_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/workspace/file': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Download File
     * @description Download a workspace file.
     */
    get: operations['download_file_api_workspace_file_get']
    put?: never
    post?: never
    /**
     * Delete Path
     * @description Delete a file, or a folder (``recursive=true`` removes its contents).
     */
    delete: operations['delete_path_api_workspace_file_delete']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/workspace/info': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * File Info
     * @description Size, mtime, MIME and blake3 (cached by path + mtime) of one file.
     */
    get: operations['file_info_api_workspace_info_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/workspace/mkdir': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Make Directory
     * @description Create a folder (and parents) inside the workspace.
     */
    post: operations['make_directory_api_workspace_mkdir_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/workspace/select': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Select Workspace
     * @description Switch the server to another workspace folder (closing every open workflow).
     */
    post: operations['select_workspace_api_workspace_select_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/workspace/sniff': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Sniff File
     * @description Guess the data kind of a file and the ``core.io.load_*`` node that reads it.
     */
    get: operations['sniff_file_api_workspace_sniff_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/workspace/tree': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Workspace Tree
     * @description Entries of a folder, folders first; nested folders beyond ``depth`` are listed lazily.
     */
    get: operations['workspace_tree_api_workspace_tree_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/workspace/upload': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Upload File
     * @description Store an uploaded file in the workspace.
     *
     *     Files above 100 MB should be sent as ordered chunks sharing an ``upload_id``; the file lands
     *     at its final path when the last chunk (``chunk_index == chunk_count - 1``) arrives.
     */
    post: operations['upload_file_api_workspace_upload_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    /**
     * BatchBinding
     * @description One table column feeding one node param (``layouts.batch.columns`` entry).
     */
    BatchBinding: {
      /** Column */
      column: string
      /** Node */
      node: string
      /** Param */
      param: string
    }
    /**
     * BatchCollect
     * @description One node output gathered into the results table.
     */
    BatchCollect: {
      /** Node */
      node: string
      /** Port */
      port: string
      /**
       * Prefix
       * @description Column prefix; defaults to none for a single collect and '<node>.' when several outputs are gathered.
       */
      prefix?: string | null
    }
    /**
     * BatchInfo
     * @description A batch's state; ``results`` is filled in as rows finish.
     */
    BatchInfo: {
      /** Batch Id */
      batch_id: string
      /** Counts */
      counts: {
        [key: string]: number
      }
      /** Finished */
      finished?: number | null
      /** N Rows */
      n_rows: number
      results: components['schemas']['BatchResults']
      /** Rows */
      rows: components['schemas']['BatchRowInfo'][]
      /** Started */
      started: number
      /** Status */
      status: string
      /** Workflow Id */
      workflow_id: string
    }
    /**
     * BatchRequest
     * @description Rows plus the spec; omitting ``spec`` uses the document's ``layouts.batch``.
     */
    BatchRequest: {
      /** Rows */
      rows?: {
        [key: string]: unknown
      }[]
      spec?: components['schemas']['BatchSpec'] | null
    }
    /**
     * BatchResults
     * @description The results grid: one row per input row, JSON-safe so it can travel over REST.
     */
    BatchResults: {
      /** Columns */
      columns?: string[]
      /** Rows */
      rows?: {
        [key: string]: unknown
      }[]
    }
    /** BatchRowInfo */
    BatchRowInfo: {
      /** Elapsed Ms */
      elapsed_ms?: number | null
      /** Error */
      error?: string | null
      /** Index */
      index: number
      /**
       * State
       * @enum {string}
       */
      state: 'pending' | 'queued' | 'running' | 'done' | 'error' | 'cancelled'
    }
    /**
     * BatchSpec
     * @description What to vary and what to keep from a batch run.
     */
    BatchSpec: {
      /** Bindings */
      bindings?: components['schemas']['BatchBinding'][]
      /** Collect */
      collect?: components['schemas']['BatchCollect'][]
      /**
       * Continue On Error
       * @default true
       */
      continue_on_error: boolean
      /**
       * Max Workers
       * @description Rows in flight; default cpu-1 with expensive nodes, else 8.
       */
      max_workers?: number | null
    }
    /** Body_upload_file_api_workspace_upload_post */
    Body_upload_file_api_workspace_upload_post: {
      /**
       * Chunk Count
       * @default 1
       */
      chunk_count: number
      /**
       * Chunk Index
       * @default 0
       */
      chunk_index: number
      /**
       * Dir
       * @description Target folder, workspace-relative.
       * @default uploads
       */
      dir: string
      /**
       * File
       * @description The file (or one chunk of it).
       */
      file: string
      /** Filename */
      filename?: string | null
      /**
       * On Conflict
       * @default error
       * @enum {string}
       */
      on_conflict: 'error' | 'rename' | 'overwrite'
      /**
       * Overwrite
       * @default false
       */
      overwrite: boolean
      /**
       * Upload Id
       * @description Set for chunked uploads.
       */
      upload_id?: string | null
    }
    /** CancelResult */
    CancelResult: {
      /** Cancelled */
      cancelled: boolean
    }
    /**
     * EdgeDoc
     * @description ``{"from": [node, port], "to": [node, port]}``.
     */
    EdgeDoc: {
      /** From */
      from: [string, string]
      /** To */
      to: [string, string]
    }
    /** EntryModel */
    EntryModel: {
      /**
       * Children
       * @description ``None`` for folders not yet listed (lazy).
       */
      children?: components['schemas']['EntryModel'][] | null
      /** Is Dir */
      is_dir: boolean
      /** Mime */
      mime?: string | null
      /**
       * Mtime
       * @default 0
       */
      mtime: number
      /** Name */
      name: string
      /** Path */
      path: string
      /**
       * Size
       * @default 0
       */
      size: number
    }
    /** FileInfoModel */
    FileInfoModel: {
      /** Blake3 */
      blake3?: string | null
      /** Mime */
      mime?: string | null
      /** Mtime */
      mtime: number
      /** Name */
      name: string
      /** Path */
      path: string
      /** Size */
      size: number
    }
    /** GroupDoc */
    GroupDoc: {
      /** Color */
      color?: string | null
      /** Nodes */
      nodes?: string[]
      /**
       * Title
       * @default
       */
      title: string
    } & {
      [key: string]: unknown
    }
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components['schemas']['ValidationError'][]
    }
    /**
     * HealthResponse
     * @description Liveness probe payload.
     */
    HealthResponse: {
      /**
       * Status
       * @constant
       */
      status: 'ok'
      /** Version */
      version: string
    }
    /**
     * InstantiateRequest
     * @description Optional overrides when creating a workflow from a template.
     */
    InstantiateRequest: {
      /** Name */
      name?: string | null
    }
    /**
     * LayoutIssue
     * @description One problem with a layout section, addressed by layout name and item position.
     */
    LayoutIssue: {
      /**
       * Code
       * @enum {string}
       */
      code:
        | 'bad_layout'
        | 'bad_ref'
        | 'unknown_promoted'
        | 'unknown_view'
        | 'unknown_node'
        | 'duplicate_view'
      /** Index */
      index?: number | null
      /** Layout */
      layout: string
      /** Message */
      message: string
      /** Ref */
      ref?: string | null
    }
    /** MkdirRequest */
    MkdirRequest: {
      /** Path */
      path: string
    }
    /**
     * NodeDoc
     * @description One node instance on the canvas.
     */
    NodeDoc: {
      /** Cost */
      cost?: ('cheap' | 'expensive' | 'auto') | null
      /**
       * Disabled
       * @default false
       */
      disabled: boolean
      /** Linked */
      linked?: string[]
      /**
       * Notes
       * @default
       */
      notes: string
      /** Params */
      params?: {
        [key: string]: unknown
      }
      /** Pos */
      pos?: [number, number] | null
      /** Size */
      size?: [number, number] | null
      /** Title */
      title?: string | null
      /** Type */
      type: string
      /** Ui */
      ui?: {
        [key: string]: unknown
      }
      /** Version */
      version?: string | null
    } & {
      [key: string]: unknown
    }
    /**
     * NodeIssue
     * @description One compile-time problem on a node (returned per node like ComfyUI's ``node_errors``).
     */
    NodeIssue: {
      /** Code */
      code: string
      /** Message */
      message: string
      /** Param */
      param?: string | null
      /** Port */
      port?: string | null
    }
    /** NodeRunInfo */
    NodeRunInfo: {
      /**
       * Cache Hit
       * @default false
       */
      cache_hit: boolean
      /** Elapsed Ms */
      elapsed_ms?: number | null
      /** Error */
      error?: string | null
      /** Key */
      key: string
      /** Node Id */
      node_id: string
      /** Status */
      status: string
    }
    /**
     * NodeSpec
     * @description Everything the frontend and engine need to know about a node type.
     */
    NodeSpec: {
      /** Category */
      category: string
      /**
       * Cost
       * @default cheap
       * @enum {string}
       */
      cost: 'cheap' | 'expensive' | 'auto'
      /**
       * Deprecated
       * @default false
       */
      deprecated: boolean
      /**
       * Description
       * @default
       */
      description: string
      /** Editor */
      editor?: string | null
      /**
       * Expand
       * @default false
       */
      expand: boolean
      /**
       * Experimental
       * @default false
       */
      experimental: boolean
      /**
       * Fingerprint
       * @description True when the node declares a ``fingerprint`` callable.
       * @default false
       */
      fingerprint: boolean
      /** Icon */
      icon?: string | null
      /** Id */
      id: string
      /**
       * Inputs
       * @default []
       */
      inputs: components['schemas']['PortSpec'][]
      /**
       * Is Async
       * @default false
       */
      is_async: boolean
      /**
       * Module
       * @default
       */
      module: string
      /** Name */
      name: string
      /**
       * Outputs
       * @default []
       */
      outputs: components['schemas']['PortSpec'][]
      /** Pack */
      pack?: string | null
      /**
       * Param Docs
       * @default {}
       */
      param_docs: {
        [key: string]: string
      }
      /**
       * Params
       * @default []
       */
      params: components['schemas']['ParamSpec'][]
      /** Preview */
      preview?: string | null
      /**
       * Version
       * @default 1.0.0
       */
      version: string
    }
    /** NodeStatus */
    NodeStatus: {
      /**
       * Cache Hit
       * @default false
       */
      cache_hit: boolean
      /**
       * Cost Class
       * @default cheap
       * @enum {string}
       */
      cost_class: 'cheap' | 'expensive' | 'auto'
      /** Elapsed Ms */
      elapsed_ms?: number | null
      /** Node Id */
      node_id: string
      /** Run Id */
      run_id?: string | null
      /**
       * Stale
       * @default false
       */
      stale: boolean
      /**
       * State
       * @enum {string}
       */
      state: 'idle' | 'dirty' | 'queued' | 'running' | 'done' | 'error' | 'cancelled'
      /** Ts */
      ts?: number
      /**
       * Type
       * @default node.status
       * @constant
       */
      type: 'node.status'
      /** Workflow Id */
      workflow_id: string
    }
    /**
     * PackInfo
     * @description Summary of a discovered node pack (full detail at ``/api/packs``).
     */
    PackInfo: {
      /**
       * Enabled
       * @default true
       */
      enabled: boolean
      /** Error */
      error?: string | null
      /** Name */
      name: string
      /**
       * Node Count
       * @default 0
       */
      node_count: number
      /**
       * Security
       * @default standard
       */
      security: string
      /** Version */
      version: string
    }
    /**
     * PackLoadError
     * @description Recorded (not raised) when a pack's entry point fails to import or register.
     */
    PackLoadError: {
      /** Entry Point */
      entry_point: string
      /** Error */
      error: string
      /** Pack */
      pack: string
      /**
       * Traceback
       * @default
       */
      traceback: string
    }
    /**
     * PackRecord
     * @description A discovered pack (entry point in the ``astro_canvas.nodes`` group).
     */
    PackRecord: {
      /** Distribution */
      distribution?: string | null
      /**
       * Enabled
       * @default true
       */
      enabled: boolean
      /** Entry Point */
      entry_point: string
      error?: components['schemas']['PackLoadError'] | null
      /** Name */
      name: string
      /**
       * Node Count
       * @default 0
       */
      node_count: number
      /**
       * Security
       * @description Manifest security class: standard, needs-network or runs-subprocess.
       * @default standard
       */
      security: string
      /**
       * Type Count
       * @default 0
       */
      type_count: number
      /**
       * Version
       * @default unknown
       */
      version: string
    }
    /**
     * ParamSpec
     * @description A widget-rendered parameter. Any param can be linked to become an input port.
     */
    ParamSpec: {
      /**
       * Advanced
       * @default false
       */
      advanced: boolean
      /** Default */
      default?: unknown
      /**
       * Description
       * @default
       */
      description: string
      /**
       * Json Schema
       * @description Self-contained JSON Schema (draft 2020-12) including default/constraints.
       */
      json_schema: {
        [key: string]: unknown
      }
      /** Label */
      label: string
      /**
       * Link Type
       * @description Port type id the param becomes when linked (``astro.Float`` etc.).
       */
      link_type: string
      /**
       * Linkable
       * @default true
       */
      linkable: boolean
      /** Name */
      name: string
      /**
       * Required
       * @default false
       */
      required: boolean
      /** Step */
      step?: number | null
      /** Unit */
      unit?: string | null
      /** Widget */
      widget?: string | null
    }
    /**
     * PortSpec
     * @description An input or output port.
     */
    PortSpec: {
      /**
       * Description
       * @default
       */
      description: string
      /**
       * Lazy
       * @default false
       */
      lazy: boolean
      /** Name */
      name: string
      /**
       * Required
       * @default true
       */
      required: boolean
      /**
       * Type
       * @description Port type id, e.g. ``astro.Spectrum1D``.
       */
      type: string
    }
    /**
     * PortTypeSpec
     * @description A registered port type.
     */
    PortTypeSpec: {
      /**
       * Color
       * @default #888888
       */
      color: string
      /**
       * Compatible With
       * @default []
       */
      compatible_with: string[]
      /**
       * Description
       * @default
       */
      description: string
      /** Id */
      id: string
      /**
       * Json Schema
       * @default {}
       */
      json_schema: {
        [key: string]: unknown
      }
      /**
       * Module
       * @default
       */
      module: string
      /** Name */
      name: string
      /** Pack */
      pack?: string | null
      /** Summary Renderer */
      summary_renderer?: string | null
    }
    /**
     * PromotedDoc
     * @description A param lifted out of a node so a layout (or a subgraph instance) can set it.
     *
     *     ``ref`` (``"<node>.<param>"``) is how layouts and subgraph instances address it.
     */
    PromotedDoc: {
      /** Group */
      group?: string | null
      /** Label */
      label?: string | null
      /** Node */
      node: string
      /**
       * Order
       * @default 0
       */
      order: number
      /** Param */
      param: string
    } & {
      [key: string]: unknown
    }
    /** RunAccepted */
    RunAccepted: {
      /** Run Id */
      run_id: string
      /** Workflow Id */
      workflow_id: string
    }
    /** RunDetail */
    RunDetail: {
      /** Finished */
      finished?: string | null
      /** Id */
      id: string
      /**
       * Nodes
       * @default []
       */
      nodes: components['schemas']['NodeRunInfo'][]
      /** Started */
      started: string
      /** Status */
      status: string
      /** Targets */
      targets?: string[] | null
      /** Workflow Id */
      workflow_id: string
    }
    /** RunRequest */
    RunRequest: {
      /**
       * Targets
       * @description Node ids to run to (default: every leaf node).
       */
      targets?: string[] | null
    }
    /** SelectRequest */
    SelectRequest: {
      /**
       * Create
       * @default false
       */
      create: boolean
      /**
       * Path
       * @description Absolute path of the folder to open as the workspace.
       */
      path: string
    }
    /** SniffResult */
    SniffResult: {
      /**
       * Detail
       * @default
       */
      detail: string
      /**
       * Kind
       * @enum {string}
       */
      kind: 'spectrum' | 'image' | 'cube' | 'table' | 'unknown'
      /** Node */
      node?: string | null
      /** Path */
      path: string
    }
    /**
     * SubgraphDoc
     * @description A reusable body. Instances are nodes typed ``subgraph:<id>``.
     *
     *     ``inputs``/``outputs`` name the boundary ports; ``promoted`` lists the inner params an
     *     instance may override through its own ``params`` (keyed by ``"<inner node>.<param>"``) or
     *     link to an input port through its own ``linked``.
     */
    SubgraphDoc: {
      /** Edges */
      edges?: {
        [key: string]: components['schemas']['EdgeDoc']
      }
      /** Inputs */
      inputs?: components['schemas']['SubgraphPort'][]
      /**
       * Name
       * @default
       */
      name: string
      /** Nodes */
      nodes?: {
        [key: string]: components['schemas']['NodeDoc']
      }
      /** Outputs */
      outputs?: components['schemas']['SubgraphPort'][]
      /** Promoted */
      promoted?: components['schemas']['PromotedDoc'][]
    } & {
      [key: string]: unknown
    }
    /**
     * SubgraphPort
     * @description An exposed port of a subgraph: ``name`` outside maps to ``node.port`` inside.
     */
    SubgraphPort: {
      /** Name */
      name: string
      /** Node */
      node: string
      /** Port */
      port: string
    }
    /**
     * SystemInfo
     * @description Environment report shown in the shell's About panel.
     */
    SystemInfo: {
      /** Disk Free Bytes */
      disk_free_bytes: number
      /** Disk Total Bytes */
      disk_total_bytes: number
      /** Packs */
      packs: components['schemas']['PackInfo'][]
      /** Platform */
      platform: string
      /** Python */
      python: string
      /** Version */
      version: string
      /** Workspace */
      workspace: string
      /** Workspace Exists */
      workspace_exists: boolean
    }
    /**
     * TemplateInfo
     * @description A workflow template a pack ships (``GET /api/templates``).
     */
    TemplateInfo: {
      /**
       * Description
       * @default
       */
      description: string
      /** File */
      file: string
      /** Id */
      id: string
      /** Name */
      name: string
      /**
       * Node Count
       * @default 0
       */
      node_count: number
      /** Pack */
      pack: string
      /** Readme */
      readme?: string | null
    }
    /** TreeResponse */
    TreeResponse: {
      /** Entries */
      entries: components['schemas']['EntryModel'][]
      /** Path */
      path: string
    }
    /** UploadResult */
    UploadResult: {
      /** Complete */
      complete: boolean
      file?: components['schemas']['FileInfoModel'] | null
      /** Received */
      received: number
      /** Upload Id */
      upload_id?: string | null
    }
    /** ValidationError */
    ValidationError: {
      /** Context */
      ctx?: Record<string, never>
      /** Input */
      input?: unknown
      /** Location */
      loc: (string | number)[]
      /** Message */
      msg: string
      /** Error Type */
      type: string
    }
    /** ViewDoc */
    ViewDoc: {
      /** Id */
      id: string
      /** Kind */
      kind?: string | null
      /** Node */
      node: string
      /** Port */
      port: string
    } & {
      [key: string]: unknown
    }
    /**
     * WorkflowDoc
     * @description The canvas document. Unknown top-level fields are preserved.
     */
    WorkflowDoc: {
      /**
       * Description
       * @default
       */
      description: string
      /** Edges */
      edges?: {
        [key: string]: components['schemas']['EdgeDoc']
      }
      /**
       * Format
       * @default astro-canvas/workflow
       * @constant
       */
      format: 'astro-canvas/workflow'
      /** Groups */
      groups?: {
        [key: string]: components['schemas']['GroupDoc']
      }
      /** Id */
      id?: string
      /** Layouts */
      layouts?: {
        [key: string]: unknown
      }
      /** Meta */
      meta?: {
        [key: string]: unknown
      }
      /**
       * Name
       * @default Untitled
       */
      name: string
      /** Nodes */
      nodes?: {
        [key: string]: components['schemas']['NodeDoc']
      }
      /** Promoted */
      promoted?: components['schemas']['PromotedDoc'][]
      /** Requires */
      requires?: {
        [key: string]: unknown
      }
      /** Subgraphs */
      subgraphs?: {
        [key: string]: components['schemas']['SubgraphDoc']
      }
      /**
       * Version
       * @default 1
       * @constant
       */
      version: 1
      /** Views */
      views?: components['schemas']['ViewDoc'][]
    } & {
      [key: string]: unknown
    }
    /**
     * WorkflowSaved
     * @description A stored document plus the compile result for its current content.
     */
    WorkflowSaved: {
      doc: components['schemas']['WorkflowDoc']
      /** Layout Errors */
      layout_errors?: components['schemas']['LayoutIssue'][]
      /** Node Errors */
      node_errors: {
        [key: string]: components['schemas']['NodeIssue'][]
      }
    }
    /**
     * WorkflowSettings
     * @description Per-workflow scheduler switches (kept in memory for the server's lifetime).
     */
    WorkflowSettings: {
      /**
       * Auto Run
       * @default true
       */
      auto_run: boolean
    }
    /** WorkflowStatus */
    WorkflowStatus: {
      /**
       * Auto Run
       * @default true
       */
      auto_run: boolean
      /** Current Run */
      current_run?: string | null
      /** Node Errors */
      node_errors: {
        [key: string]: components['schemas']['NodeIssue'][]
      }
      /** Nodes */
      nodes: {
        [key: string]: components['schemas']['NodeStatus']
      }
      /** Workflow Id */
      workflow_id: string
    }
    /** WorkflowSummary */
    WorkflowSummary: {
      /** Created */
      created: string
      /**
       * Description
       * @default
       */
      description: string
      /** Hash */
      hash: string
      /** Id */
      id: string
      /** Modified */
      modified: string
      /** Name */
      name: string
      /** Node Count */
      node_count: number
    }
    /** WorkflowVersionInfo */
    WorkflowVersionInfo: {
      /** Created */
      created: string
      /** Id */
      id: number
      /** Label */
      label?: string | null
    }
    /**
     * WorkspaceInfo
     * @description The active workspace and the user's recent ones.
     */
    WorkspaceInfo: {
      /**
       * Downloads Dir
       * @default downloads
       */
      downloads_dir: string
      /** Name */
      name: string
      /**
       * Recent
       * @default []
       */
      recent: string[]
      /** Root */
      root: string
      /**
       * Samples Dir
       * @default samples
       */
      samples_dir: string
      /**
       * Uploads Dir
       * @default uploads
       */
      uploads_dir: string
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  health_api_health_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HealthResponse']
        }
      }
    }
  }
  list_nodes_api_nodes_get: {
    parameters: {
      query?: {
        category?: string | null
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['NodeSpec'][]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_node_api_nodes__node_id__get: {
    parameters: {
      query?: never
      header?: never
      path: {
        node_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['NodeSpec']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_output_api_outputs__node_id___port__get: {
    parameters: {
      query: {
        /** @description Workflow the node belongs to. */
        workflow_id: string
        fmt?: 'json' | 'msgpack' | 'arrow' | 'npz'
        decimate?: number | null
        /** @description ``lo,hi`` on the x axis. */
        range?: string | null
      }
      header?: never
      path: {
        node_id: string
        port: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': unknown
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  list_packs_api_packs_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['PackRecord'][]
        }
      }
    }
  }
  list_runs_api_runs_get: {
    parameters: {
      query?: {
        workflow_id?: string | null
        limit?: number
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['RunDetail'][]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_run_api_runs__run_id__get: {
    parameters: {
      query?: never
      header?: never
      path: {
        run_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['RunDetail']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  cancel_run_api_runs__run_id__cancel_post: {
    parameters: {
      query?: never
      header?: never
      path: {
        run_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['CancelResult']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  system_api_system_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['SystemInfo']
        }
      }
    }
  }
  get_templates_api_templates_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['TemplateInfo'][]
        }
      }
    }
  }
  get_template_api_templates__template_id__get: {
    parameters: {
      query?: never
      header?: never
      path: {
        template_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['WorkflowDoc']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  instantiate_template_api_templates__template_id__instantiate_post: {
    parameters: {
      query?: never
      header?: never
      path: {
        template_id: string
      }
      cookie?: never
    }
    requestBody?: {
      content: {
        'application/json': components['schemas']['InstantiateRequest'] | null
      }
    }
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['WorkflowSaved']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  list_types_api_types_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['PortTypeSpec'][]
        }
      }
    }
  }
  list_workflows_api_workflows_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['WorkflowSummary'][]
        }
      }
    }
  }
  create_workflow_api_workflows_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['WorkflowDoc']
      }
    }
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['WorkflowSaved']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_workflow_api_workflows__workflow_id__get: {
    parameters: {
      query?: never
      header?: never
      path: {
        workflow_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['WorkflowDoc']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  put_workflow_api_workflows__workflow_id__put: {
    parameters: {
      query?: never
      header?: never
      path: {
        workflow_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['WorkflowDoc']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['WorkflowSaved']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  delete_workflow_api_workflows__workflow_id__delete: {
    parameters: {
      query?: never
      header?: never
      path: {
        workflow_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  start_batch_api_workflows__workflow_id__batch_post: {
    parameters: {
      query?: never
      header?: never
      path: {
        workflow_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['BatchRequest']
      }
    }
    responses: {
      /** @description Successful Response */
      202: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['BatchInfo']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_batch_api_workflows__workflow_id__batch__batch_id__get: {
    parameters: {
      query?: never
      header?: never
      path: {
        workflow_id: string
        batch_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['BatchInfo']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  cancel_batch_api_workflows__workflow_id__batch__batch_id__cancel_post: {
    parameters: {
      query?: never
      header?: never
      path: {
        workflow_id: string
        batch_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['BatchInfo']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  start_run_api_workflows__workflow_id__run_post: {
    parameters: {
      query?: never
      header?: never
      path: {
        workflow_id: string
      }
      cookie?: never
    }
    requestBody?: {
      content: {
        'application/json': components['schemas']['RunRequest'] | null
      }
    }
    responses: {
      /** @description Successful Response */
      202: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['RunAccepted']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_settings_api_workflows__workflow_id__settings_get: {
    parameters: {
      query?: never
      header?: never
      path: {
        workflow_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['WorkflowSettings']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  update_settings_api_workflows__workflow_id__settings_post: {
    parameters: {
      query?: never
      header?: never
      path: {
        workflow_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['WorkflowSettings']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['WorkflowSettings']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  workflow_status_api_workflows__workflow_id__status_get: {
    parameters: {
      query?: never
      header?: never
      path: {
        workflow_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['WorkflowStatus']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  list_versions_api_workflows__workflow_id__versions_get: {
    parameters: {
      query?: never
      header?: never
      path: {
        workflow_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['WorkflowVersionInfo'][]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_version_api_workflows__workflow_id__versions__version_id__get: {
    parameters: {
      query?: never
      header?: never
      path: {
        workflow_id: string
        version_id: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['WorkflowDoc']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  workspace_info_api_workspace_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['WorkspaceInfo']
        }
      }
    }
  }
  download_file_api_workspace_file_get: {
    parameters: {
      query: {
        /** @description Workspace-relative file path. */
        path: string
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': unknown
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  delete_path_api_workspace_file_delete: {
    parameters: {
      query: {
        /** @description Workspace-relative file or (empty) folder. */
        path: string
        recursive?: boolean
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  file_info_api_workspace_info_get: {
    parameters: {
      query: {
        /** @description Workspace-relative file path. */
        path: string
        hash?: boolean
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['FileInfoModel']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  make_directory_api_workspace_mkdir_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['MkdirRequest']
      }
    }
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['EntryModel']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  select_workspace_api_workspace_select_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['SelectRequest']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['WorkspaceInfo']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  sniff_file_api_workspace_sniff_get: {
    parameters: {
      query: {
        /** @description Workspace-relative file path. */
        path: string
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['SniffResult']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  workspace_tree_api_workspace_tree_get: {
    parameters: {
      query?: {
        /** @description Workspace-relative folder (``''`` = root). */
        path?: string
        depth?: number
        hidden?: boolean
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['TreeResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  upload_file_api_workspace_upload_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'multipart/form-data': components['schemas']['Body_upload_file_api_workspace_upload_post']
      }
    }
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['UploadResult']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
}
