"""``rbcodes.zfind.*`` nodes: known-redshift recovery on the sample spectra, ranking, catalogues.

The SDSS pipeline gives z = 0.00586 for ``spec-0398-51789-0282.fits`` (star-forming galaxy) and
z = 3.0133 for ``sdss1.fits`` (quasar); ``fixtures/reference_zfind.json`` holds what rbcodes'
own engine returns for the same inputs (generated by ``generate_reference_zfind.py`` on 3.10).
"""

from __future__ import annotations

import asyncio
import json
from pathlib import Path
from typing import Any

import numpy as np
import pytest
from astro_canvas_core.nodes.io import load_spectrum
from astro_canvas_core.types import LineList, Redshift, Spectrum1D, Table
from astro_canvas_rbcodes.nodes import absorption as A
from astro_canvas_rbcodes.nodes import zfind as N
from astro_canvas_rbcodes.types import AbsorberResult, ZCandidates, ZCurve, ZFindResult, ZSolution

from astro_canvas.cli import run_headless
from astro_canvas.engine.graph import WorkflowDoc
from astro_canvas.engine.graph import compile as compile_workflow
from astro_canvas.sdk import NullContext, discover
from astro_canvas.settings import Settings
from tests.packs.rbcodes.conftest import FIXTURES, SAMPLES

TEMPLATE = (
    Path(__file__).resolve().parents[4] / "packs" / "rbcodes" / "templates" / "redshift-finder.acw"
)
GALAXY_Z = 0.00586
QSO_Z = 3.0133
Z_TOL = 0.002
"""rbcodes' own tolerance for grid-limited line searches (0.5 pixel / rest wavelength)."""
# Cross-environment (3.10 rbcodes vs 3.12 kernels, different numpy/scipy builds) the curves agree
# far better than this; identical arrays agree to 1e-9 (test_zfind_matches_rbcodes.py).
REL = 1e-6


@pytest.fixture(scope="module")
def galaxy() -> Spectrum1D:
    return load_spectrum(path="spec-0398-51789-0282.fits", ctx=NullContext(workspace=SAMPLES))


@pytest.fixture(scope="module")
def galaxy_f64() -> Spectrum1D:
    """Parsed by Astro Canvas itself (float64 grid), as the reference fixture was generated."""
    return load_spectrum(
        path="spec-0398-51789-0282.fits", use_rbcodes=False, ctx=NullContext(workspace=SAMPLES)
    )


@pytest.fixture(scope="module")
def sdss1_f64() -> Spectrum1D:
    return load_spectrum(path="sdss1.fits", use_rbcodes=False, ctx=NullContext(workspace=SAMPLES))


@pytest.fixture(scope="module")
def zfind_reference() -> dict[str, Any]:
    data: dict[str, Any] = json.loads((FIXTURES / "reference_zfind.json").read_text("utf-8"))
    return data


def test_curated_linelist_node_and_registration() -> None:
    lines = N.curated_linelist(name="zfind_igm")
    assert isinstance(lines, LineList) and lines.source == "zfind_igm" and len(lines) == 11
    assert lines.weight is not None and lines.kind is not None
    assert set(lines.kind.tolist()) == {"absorption"}
    assert np.array_equal(lines.fval, lines.weight)
    registry = discover().registry
    for type_id in ("rbcodes.ZFindResult", "rbcodes.AbsorberResult", "rbcodes.ZCandidates"):
        assert registry.types.get(type_id).type_id() == type_id
    rank_spec = registry.get("rbcodes.zfind.rank").spec
    assert rank_spec.editor == "z-accept"
    assert [o.name for o in rank_spec.outputs] == ["redshift", "candidates"]
    assert [i.required for i in rank_spec.inputs] == [True, False, False, False]
    assert registry.get("rbcodes.zfind.pca_search").spec.cost == "expensive"
    assert registry.get("rbcodes.zfind.picket_fence_search").spec.cost == "auto"


def test_line_searches_recover_the_sdss_galaxy(galaxy: Spectrum1D) -> None:
    lines = N.curated_linelist(name="zfind_galaxy")
    ctx = NullContext()
    pf = N.picket_fence_search(
        galaxy,
        lines,
        z_min=0.0,
        z_max=0.5,
        n_steps=3000,
        smooth_fwhm_pix=2.0,
        fwhm_ang=3.0,
        ctx=ctx,
    )
    assert isinstance(pf, ZFindResult) and pf.statistic == "score"
    assert pf.best() is not None and abs(pf.best().z - GALAXY_Z) < Z_TOL
    assert pf.best().method == "PicketFence:zfind_galaxy" and pf.best().n_features == 12
    assert pf.linelist == "zfind_galaxy" and pf.curves[0].label == "PicketFence:zfind_galaxy"
    assert pf.input_spec is not None and pf.input_spec.frame == "observed"
    assert pf.input_spec.continuum is not None and pf.input_spec.meta["airvac"] == "vac"
    assert pf.meta["rbcodes"]["backend"] in ("rbcodes", "vendored")
    assert pf.meta["params"]["n_steps"] == 3000
    ls = N.line_search(galaxy, lines, z_min=0.0, z_max=0.5, n_steps=3000)
    assert ls.best() is not None and abs(ls.best().z - GALAXY_Z) < Z_TOL
    assert ls.best().method == "LineSearch:zfind_galaxy"
    # Forcing every line to "absorption" removes the emission signal at the true z.
    forced = N.picket_fence_search(
        galaxy, lines, z_min=0.0, z_max=0.5, n_steps=1000, line_type="absorption", use_error="never"
    )
    assert forced.best() is None or abs(forced.best().z - GALAXY_Z) > Z_TOL
    assert any("use_error=False" in w for w in forced.warnings)
    mode_b = N.picket_fence_search(
        galaxy, lines, z_min=0.0, z_max=0.5, n_steps=1000, pf_mode="detect_match", fwhm_ang=3.0
    )
    assert mode_b.best() is not None and mode_b.best().method.endswith(":ModeB")


def test_template_and_pca_recover_the_galaxy_with_progress_and_cancel(galaxy: Spectrum1D) -> None:
    tpl = N.template_search(
        galaxy, template_name="LateTypeEmission", z_min=0.0, z_max=0.5, n_steps=1000
    )
    assert tpl.statistic == "chi2" and tpl.best() is not None
    assert abs(tpl.best().z - GALAXY_Z) < 0.005 and tpl.best().template_type == "LateTypeEmission"
    ctx = NullContext()
    pca = N.pca_search(galaxy, template_set="galaxy", z_min=0.0, z_max=0.5, n_steps=500, ctx=ctx)
    assert pca.best() is not None and abs(pca.best().z - GALAXY_Z) < 0.005
    assert pca.best().n_features == 10 and pca.meta["rbcodes"]["backend"] == "vendored"
    fractions = [f for f, _ in ctx.progress_events]
    assert fractions[0] == 0.0 and fractions[-1] == 1.0 and len(fractions) > 10
    with pytest.raises(InterruptedError):
        N.pca_search(galaxy, template_set="galaxy", n_steps=200, ctx=NullContext(cancelled=True))
    multi = N.multi_template_search(
        galaxy, templates=["LateTypeEmission", "EarlyType"], z_min=0.0, z_max=0.2, n_steps=200
    )
    assert [c.label for c in multi.curves] == ["LateTypeEmission", "EarlyType"]
    assert multi.meta["params"]["templates"] == ["LateTypeEmission", "EarlyType"]
    all_pca = N.multi_pca_search(galaxy, template_sets=[], n_steps=60, ctx=NullContext())
    assert [c.label for c in all_pca.curves] == ["PCA:galaxy", "PCA:qso_loz", "PCA:qso_hiz"]
    assert float(all_pca.z_array[-1]) == 6.0


def test_continuum_source_and_frames(galaxy: Spectrum1D) -> None:
    lines = N.curated_linelist(name="zfind_galaxy")
    kwargs: dict[str, Any] = {"z_min": 0.0, "z_max": 0.5, "n_steps": 1000}
    # Astro Canvas' SDSS parser stores the pipeline "model" column as `continuum`; subtracting
    # it removes the lines, so the default is to fit one. (rbcodes' reader sets no continuum.)
    with_model = galaxy.model_copy(update={"continuum": np.full(len(galaxy), 2.0)})
    model = N.line_search(with_model, lines, continuum="spectrum", **kwargs)
    assert model.input_spec is not None and model.input_spec.continuum is not None
    assert np.all(model.input_spec.continuum == 2.0)
    fitted = N.line_search(with_model, lines, continuum="fit", **kwargs)
    assert fitted.input_spec is not None and fitted.input_spec.continuum is not None
    assert not np.allclose(fitted.input_spec.continuum, 2.0)
    assert fitted.best() is not None and abs(fitted.best().z - GALAXY_Z) < Z_TOL
    none = N.line_search(galaxy, lines, continuum="none", **kwargs)
    assert none.input_spec is not None and none.input_spec.continuum is None
    # Rest-frame input is shifted back to the observed frame first.
    rest = A.set_redshift(galaxy, z=GALAXY_Z)
    from_rest = N.line_search(rest, lines, **kwargs)
    assert from_rest.best() is not None and abs(from_rest.best().z - fitted.best().z) < 1e-9
    velocity = A.slice_spectrum(rest, A.set_transition(wrest=6564.61, linelist="Gal_Em"))
    with pytest.raises(ValueError, match="velocity slice"):
        N.line_search(velocity, lines, **kwargs)


def _fake(z_values: list[float], method: str, statistic: str = "score") -> ZFindResult:
    z = np.linspace(0.0, 1.0, 11)
    return ZFindResult(
        z_array=z,
        curves=[ZCurve(label=method, values=z)],
        solutions=[
            ZSolution(z=v, z_err=1e-3 * (i + 1), chi2_dof=float(i), method=method)
            for i, v in enumerate(z_values)
        ],
        statistic=statistic,  # type: ignore[arg-type]
    )


def test_rank_combines_sources_in_order_and_accepts_an_index() -> None:
    first = _fake([0.30, 0.71], "PicketFence:a")
    second = _fake([0.31], "Template:QSO", "chi2")
    redshift, cands = N.rank(first, second)
    assert isinstance(redshift, Redshift) and isinstance(cands, ZCandidates)
    assert redshift.z == 0.30 and redshift.z_err == 1e-3 and redshift.method == "PicketFence:a"
    assert redshift.source == "rbcodes.zfind.rank" and cands.accepted == 0
    assert [(r.index, r.source, r.rank, r.z) for r in cands.rows] == [
        (0, 0, 0, 0.30),
        (1, 0, 1, 0.71),
        (2, 1, 0, 0.31),
    ]
    assert cands.statistics == ["score", "chi2"]
    chosen, cands2 = N.rank(first, None, second, accepted=2)
    assert chosen.z == 0.31 and chosen.method == "Template:QSO" and cands2.accepted == 2
    with pytest.raises(ValueError, match="out of range"):
        N.rank(first, second, accepted=3)
    with pytest.raises(ValueError, match="no redshift candidates"):
        N.rank(_fake([], "empty"))
    rows, statistics = N.combine_candidates([second, first])
    assert [r.method for r in rows] == ["Template:QSO", "PicketFence:a", "PicketFence:a"]
    assert statistics == ["chi2", "score"]
    # The accepted redshift drives Set Redshift like any Redshift port.
    spectrum = Spectrum1D(wave=np.linspace(4000, 5000, 5), flux=np.ones(5))
    shifted = A.set_redshift(spectrum, z=0.0, redshift=chosen)
    assert shifted.z == 0.31 and shifted.wave[0] == pytest.approx(4000 / 1.31)


def test_absorber_search_and_catalog(sdss1: Spectrum1D) -> None:
    igm = N.curated_linelist(name="zfind_igm")
    result = N.absorber_search(sdss1, igm, z_min=0.5, z_max=2.5, n_steps=4000)
    assert isinstance(result, AbsorberResult) and result.linelist == "zfind_igm"
    assert result.candidates and result.candidates[0].significance > 3.0
    sigs = [c.significance for c in result.candidates]
    assert sigs == sorted(sigs, reverse=True)
    assert result.input_spec is not None and result.meta["rbcodes"]["backend"] in (
        "rbcodes",
        "vendored",
    )
    catalog = N.absorbers_to_catalog(result, accepted=[0, 2])
    assert isinstance(catalog, Table) and catalog.n_rows == 2
    assert list(catalog.columns) == [
        "zabs",
        "name",
        "label",
        "significance",
        "n_lines",
        "lines_matched",
    ]
    assert catalog.columns["zabs"][0] == pytest.approx(result.candidates[0].z)
    assert catalog.columns["label"][1] == f"z={result.candidates[2].z:.4f} (zfind_igm)"
    assert ", " in str(catalog.columns["lines_matched"][0]) or catalog.columns["n_lines"][0] == 1
    everything = N.absorbers_to_catalog(result)
    assert everything.n_rows == len(result.candidates)
    back = Table.from_blob(everything.to_blob())
    assert back.n_rows == everything.n_rows and str(back.columns["name"][0]) == "zfind_igm"
    with pytest.raises(ValueError, match="velocity slice"):
        N.absorber_search(
            A.slice_spectrum(A.set_redshift(sdss1, z=1.3855), A.set_transition(wrest=2796.35)), igm
        )


@pytest.mark.parametrize(
    "case_id",
    [
        "galaxy_picket_fence",
        "galaxy_line_search",
        "galaxy_template",
        "galaxy_pca",
        "qso_picket_fence",
        "qso_absorbers",
    ],
)
def test_nodes_match_rbcodes_reference(
    galaxy_f64: Spectrum1D, sdss1_f64: Spectrum1D, zfind_reference: dict[str, Any], case_id: str
) -> None:
    entry = zfind_reference["cases"][case_id]
    case, expected = entry["case"], entry["expected"]
    source = galaxy_f64 if case["file"].startswith("spec-0398") else sdss1_f64
    # The fixture was generated with a flat median continuum (see generate_reference_zfind.py).
    flat = np.full(len(source), float(np.nanmedian(source.flux)))
    spec = source.model_copy(update={"continuum": flat})
    kwargs: dict[str, Any] = {**case["kwargs"], "continuum": "spectrum"}
    method = case["method"]
    if method == "picket_fence":
        result = N.picket_fence_search(spec, N.curated_linelist(name=case["linelist"]), **kwargs)
        curve = result.curves[0].values
    elif method == "line_search" and kwargs.pop("mode") == "absorption":
        result = N.absorber_search(spec, N.curated_linelist(name=case["linelist"]), **kwargs)
        curve = result.significance_curve
    elif method == "line_search":
        result = N.line_search(spec, N.curated_linelist(name=case["linelist"]), **kwargs)
        curve = result.curves[0].values
    elif method == "template":
        result = N.template_search(spec, **kwargs)
        curve = result.curves[0].values
    else:
        result = N.pca_search(spec, **kwargs)
        curve = result.curves[0].values
    stats = expected["curve"]
    assert len(curve) == stats["n"] and int(np.isfinite(curve).sum()) == stats["n_finite"]
    assert float(result.z_array[np.nanargmin(curve)]) == pytest.approx(stats["argmin_z"], abs=1e-9)
    assert float(np.nanmin(curve)) == pytest.approx(stats["min"], rel=REL)
    for index, value in zip(stats["probe_index"], stats["probe"], strict=True):
        if value is None:
            assert not np.isfinite(curve[index])
        else:
            assert float(curve[index]) == pytest.approx(value, rel=REL, abs=1e-12)
    assert list(result.warnings) == expected["warnings"]
    if case["file"].startswith("spec-0398") and method != "template":
        # Known-z recovery (the template method needs the real continuum shape, not a flat one).
        assert isinstance(result, ZFindResult) and result.best() is not None
        assert abs(result.best().z - GALAXY_Z) < 0.005
    if isinstance(result, AbsorberResult):
        for ours, theirs in zip(result.candidates, expected["candidates"], strict=False):
            assert ours.z == pytest.approx(theirs["z"], abs=1e-9)
            assert ours.significance == pytest.approx(theirs["significance"], rel=REL)
            assert (
                ours.n_lines == theirs["n_lines"] and ours.lines_matched == theirs["lines_matched"]
            )
    else:
        assert result.curves[0].label == expected["label"]
        for ours, theirs in zip(result.solutions, expected["solutions"], strict=False):
            assert ours.z == pytest.approx(theirs["z"], abs=1e-9)
            assert ours.chi2_dof == pytest.approx(theirs["chi2_dof"], rel=REL)
            assert ours.method == theirs["method"] and ours.n_features == theirs["n_features"]
            if theirs["z_err"] is None:
                assert ours.z_err is None
            else:
                assert ours.z_err == pytest.approx(theirs["z_err"], rel=1e-4)


def test_template_compiles_and_runs_headless(tmp_path: Path) -> None:
    doc = WorkflowDoc.model_validate_json(TEMPLATE.read_text(encoding="utf-8"))
    graph = compile_workflow(doc, discover().registry)
    assert not getattr(graph, "node_errors", None) and not graph.blocked, graph
    assert set(graph.nodes) >= {"pf_gal", "rank_gal", "zshift_gal", "pf_qso", "pca_gal"}
    assert doc.views and {v.kind for v in doc.views} >= {
        "zfind-curve",
        "candidates-table",
        "spectrum",
    }
    workspace = tmp_path / "ws"
    workspace.mkdir()
    settings = Settings(
        workspace=workspace, config_dir=workspace / "config", process_pool=False, auth=False
    )
    summary = asyncio.run(run_headless(settings, TEMPLATE, None))
    states = {k: v["state"] for k, v in summary["nodes"].items()}
    for node_id in (
        "pf_gal",
        "ls_gal",
        "tpl_gal",
        "rank_gal",
        "zshift_gal",
        "pf_qso",
        "rank_qso",
        "zshift_qso",
    ):
        assert states[node_id] == "done", (node_id, summary["nodes"][node_id])
    # The CLI runs expensive nodes too (in-process here): the PCA path is exercised as well.
    assert states["pca_gal"] == "done"
    assert summary["status"] == "done"
